import { _mock } from './_mock';

// ----------------------------------------------------------------------

export const DESIGNER_CATEGORIES = [
  { value: 'haute-couture', label: 'Haute Couture' },
  { value: 'pret-a-porter', label: 'Prêt-à-Porter' },
  { value: 'sustainable-luxury', label: 'Sustainable Luxury' },
  { value: 'avant-garde', label: 'Avant-Garde' },
  { value: 'artisanal', label: 'Artisanal' },
  { value: 'bridal-couture', label: 'Bridal Couture' },
];

export const DESIGNER_SPECIALTIES = [
  { value: 'womens-wear', label: "Women's Wear" },
  { value: 'mens-wear', label: "Men's Wear" },
  { value: 'unisex', label: 'Unisex Collections' },
  { value: 'children', label: "Children's Fashion" },
  { value: 'bridal', label: 'Bridal' },
  { value: 'accessories', label: 'Accessories' },
];

export const DESIGNER_EXPERIENCE_LEVELS = [
  { value: 'icon', label: 'Industry Icons (20+ Years)' },
  { value: 'established', label: 'Established (10-20 Years)' },
  { value: 'rising', label: 'Rising Stars (5-10 Years)' },
  { value: 'emerging', label: 'Emerging Talent (<5 Years)' },
];

// Featured designers data
const featuredDesigners = [
  {
    id: _mock.id(1),
    name: 'Silvia Tcherassi',
    slug: 'silvia-tcherassi',
    category: 'Haute Couture',
    location: 'Barranquilla',
    country: 'Colombia',
    experience: 30,
    experienceLabel: '30 Years of Excellence',
    featured: true,
    verified: true,
    rating: 4.9,
    reviews: 127,
    photo: 'https://res.cloudinary.com/dzqy2ixl0/image/upload/f_auto,q_auto,w_400,h_400,c_fill,g_face/v1753881098/style_023_hgpv3i.jpg',
    coverImage: 'https://res.cloudinary.com/dzqy2ixl0/image/upload/f_auto,q_auto,w_1200,h_600,c_fill/v1753881164/fu_044_jekphp.jpg',
    specialties: ["Women's Wear", 'Bridal'],
    description: 'Internationally recognized for tropical glamour and sophisticated resort wear. As seen in Vogue, Elle, and Harper\'s Bazaar.',
    instagram: '@silviatcherassi',
    website: 'www.silviatcherassi.com',
    price: 5000, // Starting price for custom pieces
  },
  {
    id: _mock.id(2),
    name: 'Johanna Ortiz',
    slug: 'johanna-ortiz',
    category: 'Ready-to-Wear',
    location: 'Cali',
    country: 'Colombia',
    experience: 20,
    experienceLabel: '20 Years Experience',
    featured: true,
    verified: true,
    rating: 4.8,
    reviews: 98,
    photo: 'https://res.cloudinary.com/dzqy2ixl0/image/upload/f_auto,q_auto,w_400,h_400,c_fill,g_face/v1753881097/style_019_rk96sv.jpg',
    coverImage: 'https://res.cloudinary.com/dzqy2ixl0/image/upload/f_auto,q_auto,w_1200,h_600,c_fill/v1753881165/fu_051_ot4esa.jpg',
    specialties: ["Women's Wear", 'Unisex'],
    description: 'Feminine silhouettes celebrating Latin American heritage',
    instagram: '@johannaortiz',
    website: 'www.johannaortiz.com',
    price: 3000,
  },
  {
    id: _mock.id(3),
    name: 'Esteban Cortázar',
    slug: 'esteban-cortazar',
    category: 'Contemporary',
    location: 'Bogotá',
    country: 'Colombia',
    experience: 25,
    experienceLabel: '25 Years Experience',
    featured: true,
    verified: true,
    rating: 4.7,
    reviews: 86,
    photo: 'https://res.cloudinary.com/dzqy2ixl0/image/upload/f_auto,q_auto,w_400,h_400,c_fill,g_face/v1753881096/style_012_au1j7m.jpg',
    coverImage: 'https://res.cloudinary.com/dzqy2ixl0/image/upload/f_auto,q_auto,w_1200,h_600,c_fill/v1753881163/fu_045_xp9jln.jpg',
    specialties: ["Women's Wear", "Men's Wear"],
    description: 'Modern minimalism with Latin sensuality',
    instagram: '@estebancortazar',
    website: 'www.estebancortazar.com',
    price: 4000,
  },
];

// Additional designers
const additionalDesigners = [
  {
    id: _mock.id(4),
    name: 'María Villamil',
    slug: 'maria-villamil',
    category: 'Sustainable',
    location: 'Medellín',
    country: 'Colombia',
    experience: 15,
    experienceLabel: '15 Years Experience',
    featured: false,
    verified: true,
    rating: 4.6,
    reviews: 72,
    photo: 'https://res.cloudinary.com/dzqy2ixl0/image/upload/f_auto,q_auto,w_400,h_400,c_fill,g_center/v1753881238/fu_020_qvzsyb.jpg',
    coverImage: 'https://res.cloudinary.com/dzqy2ixl0/image/upload/f_auto,q_auto,w_1200,h_600,c_fill/v1753881161/fu_032_rho9fv.jpg',
    specialties: ["Women's Wear", 'Accessories'],
    description: 'Eco-conscious designs with traditional Colombian textiles',
    instagram: '@mariavillamil',
    website: 'www.villamil.co',
    price: 2000,
  },
  {
    id: _mock.id(5),
    name: 'Laura Laurens',
    slug: 'laura-laurens',
    category: 'Contemporary',
    location: 'Bogotá',
    country: 'Colombia',
    experience: 12,
    experienceLabel: '12 Years Experience',
    featured: false,
    verified: true,
    rating: 4.5,
    reviews: 64,
    photo: 'https://res.cloudinary.com/dzqy2ixl0/image/upload/f_auto,q_auto,w_400,h_400,c_fill,g_center/v1753881241/fu_041_w7ejur.jpg',
    coverImage: 'https://res.cloudinary.com/dzqy2ixl0/image/upload/f_auto,q_auto,w_1200,h_600,c_fill/v1753881161/fu_014_kplkhu.jpg',
    specialties: ["Women's Wear", 'Unisex'],
    description: 'Architectural silhouettes for the modern urbanite',
    instagram: '@lauralaurens',
    website: 'www.lauralaurens.com',
    price: 2500,
  },
  {
    id: _mock.id(6),
    name: 'Amelia Toro',
    slug: 'amelia-toro',
    category: 'Luxury',
    location: 'Cartagena',
    country: 'Colombia',
    experience: 22,
    experienceLabel: '22 Years Experience',
    featured: false,
    verified: true,
    rating: 4.4,
    reviews: 56,
    photo: 'https://res.cloudinary.com/dzqy2ixl0/image/upload/f_auto,q_auto,w_400,h_400,c_fill,g_center/v1753881240/fu_040_jf3cqa.jpg',
    coverImage: 'https://res.cloudinary.com/dzqy2ixl0/image/upload/f_auto,q_auto,w_1200,h_600,c_fill/v1753881164/fu_048_lncqda.jpg',
    specialties: ["Women's Wear", 'Accessories'],
    description: 'Timeless elegance with Caribbean influences',
    instagram: '@ameliatoro',
    website: 'www.ameliatoro.com',
    price: 3500,
  },
  {
    id: _mock.id(7),
    name: 'Pepa Pombo',
    slug: 'pepa-pombo',
    category: 'Ready-to-Wear',
    location: 'Bogotá',
    country: 'Colombia',
    experience: 18,
    experienceLabel: '18 Years Experience',
    featured: false,
    verified: true,
    rating: 4.3,
    reviews: 48,
    photo: 'https://res.cloudinary.com/dzqy2ixl0/image/upload/f_auto,q_auto,w_400,h_400,c_fill,g_center/v1753881239/fu_034_t4qeyk.jpg',
    coverImage: 'https://res.cloudinary.com/dzqy2ixl0/image/upload/f_auto,q_auto,w_1200,h_600,c_fill/v1753881238/fu_020_qvzsyb.jpg',
    specialties: ["Women's Wear", 'Bridal'],
    description: 'Romantic designs with contemporary edge',
    instagram: '@pepapombo',
    website: 'www.pepapombo.com',
    price: 2800,
  },
  {
    id: _mock.id(8),
    name: 'Andrés Pajón',
    slug: 'andres-pajon',
    category: 'Contemporary',
    location: 'Medellín',
    country: 'Colombia',
    experience: 8,
    experienceLabel: '8 Years Experience',
    featured: false,
    verified: false,
    rating: 4.2,
    reviews: 32,
    photo: 'https://res.cloudinary.com/dzqy2ixl0/image/upload/f_auto,q_auto,w_400,h_400,c_fill,g_center/v1753881241/fu_041_w7ejur.jpg',
    coverImage: 'https://res.cloudinary.com/dzqy2ixl0/image/upload/f_auto,q_auto,w_1200,h_600,c_fill/v1753881240/fu_040_jf3cqa.jpg',
    specialties: ["Men's Wear", 'Unisex'],
    description: 'Urban streetwear meets high fashion',
    instagram: '@andrespajon',
    website: 'www.andrespajon.com',
    price: 1500,
  },
];

// Generate tour-like fields for compatibility with Zone components
const generateDesignerTourData = (designer) => ({
  ...designer,
  // Map to tour fields for Zone compatibility
  duration: `${designer.experience} Years`,
  continent: 'South America',
  priceSale: designer.price * 0.8,
  gallery: [
    designer.coverImage,
    'https://res.cloudinary.com/dzqy2ixl0/image/upload/f_auto,q_auto,w_800,h_600,c_fill/v1753881165/fu_051_ot4esa.jpg',
    'https://res.cloudinary.com/dzqy2ixl0/image/upload/f_auto,q_auto,w_800,h_600,c_fill/v1753881163/fu_045_xp9jln.jpg',
    'https://res.cloudinary.com/dzqy2ixl0/image/upload/f_auto,q_auto,w_800,h_600,c_fill/v1753881161/fu_032_rho9fv.jpg',
  ],
  tourGuide: {
    name: designer.name,
    role: designer.category + ' Designer',
    photo: designer.photo,
    verified: designer.verified,
  },
  highlights: designer.specialties,
  services: designer.specialties,
  languages: ['Spanish', 'English'],
  tags: designer.specialties,
  content: designer.description,
});

// Export designers with tour compatibility
export const _designers = [...featuredDesigners, ...additionalDesigners].map(
  generateDesignerTourData
);
